default_platform(:ios)

platform :ios do
  before_all do
    Dotenv.load ".env"
    Dotenv.load ".env.ios"
  end

  desc "Runs tests"
  lane :test do
    xcode_select ENV['FL_XCODE_PATH']
    run_tests
  end

  error do |lane, exception|
  end
end
